name: poultry_app
description: Flutter multi-platform poultry app (final)
version: 1.0.0

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  fl_chart: ^0.68.0
  path_provider: ^2.0.15
  http: ^1.2.3
  pdf: ^3.11.0
  printing: ^5.10.1
  connectivity_plus: ^7.0.0
  supabase_flutter: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  build_runner: ^2.4.5
  hive_generator: ^2.0.1
